# From: https://github.com/chainguard-dev/policy-catalog/blob/69682e48a22fb66c60302a7fc5f62824a40a707c/policies/benchmarks/pod-security-standards/hostpath-volumes-cue.yaml#L7

# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: hostpath-volumes-cue
  annotations:
    catalog.chainguard.dev/title: Disallow hostpath volumes
    catalog.chainguard.dev/labels: cue,workloads
    catalog.chainguard.dev/description: |
      HostPath volumes must be forbidden.

    catalog.chainguard.dev/learnMoreLink: https://kubernetes.io/docs/concepts/security/pod-security-standards/#baseline
spec:
  match:
  - version: "v1"
    resource: "pods"
  images: [glob: '**']
  authorities: [static: {action: pass}]
  mode: warn
  policy:
    includeSpec: true
    type: "cue"
    data: |
      spec: {
        volumes: [...{
          hostPath:
            path: ""
        }]
      }
